/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Apresentacao;

import Modelo.DesmatamentoAmaz;
import Modelo.Estatico;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gabri
 */
public class frmConsultaArea extends javax.swing.JDialog {

    void preencherTabela()
    {
        //tblPesquisaPessoas.setModel(new DefaultTableModel(new Object[][]{}, new String[] {"ID", "NOME", "RG", "CPF"}));
        DefaultTableModel modelo = (DefaultTableModel) tblResultado.getModel();
        modelo.setNumRows(0);
        
        for(int d : Estatico.listaRe)
        {
            modelo.addRow(new Object[]
            {
                 d
            });
        }
    }
    /**
     * Creates new form frmConsultaArea
     */
    public frmConsultaArea(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAreaDesmatada = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultado = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblTempoOrde = new javax.swing.JLabel();
        btnMAreaDesmatada = new javax.swing.JButton();
        lblAno = new javax.swing.JLabel();
        txFAno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnAreaDesmatada.setText("Buscar Por Menor Area Desmatada");
        btnAreaDesmatada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaDesmatadaActionPerformed(evt);
            }
        });

        tblResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Area Desmatada em Km²"
            }
        ));
        jScrollPane1.setViewportView(tblResultado);

        jLabel1.setText("Tempo para Ordenação");

        lblTempoOrde.setText("ms");

        btnMAreaDesmatada.setText("Buscar Por Maior Area Desmatada");
        btnMAreaDesmatada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMAreaDesmatadaActionPerformed(evt);
            }
        });

        lblAno.setText("Ano");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addComponent(lblAno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txFAno, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAreaDesmatada)
                .addGap(18, 18, 18)
                .addComponent(btnMAreaDesmatada)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblTempoOrde, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAreaDesmatada)
                    .addComponent(btnMAreaDesmatada)
                    .addComponent(txFAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTempoOrde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAreaDesmatadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaDesmatadaActionPerformed
        // TODO add your handling code here:
        Modelo.Controle controle = new Modelo.Controle();
        if(txFAno.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Por Favor digite um Ano Valido.");
        else  
            Estatico.listaRe = controle.pesquisarPorDesmatamento(txFAno.getText());
        if (!controle.getMensagem().equals(""))
        {
            JOptionPane.showMessageDialog(null, controle.getMensagem());
            return;
        }
        if (Estatico.listaRe.length == 0)
        {
            JOptionPane.showMessageDialog(null, "Não existe resultado para esta pesquisa");
        }
        if (Estatico.listaRe.length > 1)
        {

            preencherTabela();
            lblTempoOrde.setText(Estatico.tempoLevado.toString());
        }

    }//GEN-LAST:event_btnAreaDesmatadaActionPerformed

    private void btnMAreaDesmatadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMAreaDesmatadaActionPerformed
        // TODO add your handling code here:
        Modelo.Controle controle = new Modelo.Controle();
        if(txFAno.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Por Favor digite um Ano Valido.");
        else
            Estatico.listaRe = controle.pesquisarMaiorPorDesmatamento(txFAno.getText());
        if (!controle.getMensagem().equals(""))
        {
            JOptionPane.showMessageDialog(null, controle.getMensagem());
            return;
        }
        if (Estatico.listaRe.length == 0)
        {
            JOptionPane.showMessageDialog(null, "Não existe resultado para esta pesquisa");
        }
        if (Estatico.listaRe.length > 1)
        {
            preencherTabela();
            if(Estatico.listaResultado.size() > 1)
            lblTempoOrde.setText(Estatico.tempoLevado.toString());
        }
    }//GEN-LAST:event_btnMAreaDesmatadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmConsultaArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmConsultaArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmConsultaArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmConsultaArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmConsultaArea dialog = new frmConsultaArea(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAreaDesmatada;
    private javax.swing.JButton btnMAreaDesmatada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblTempoOrde;
    private javax.swing.JTable tblResultado;
    private javax.swing.JTextField txFAno;
    // End of variables declaration//GEN-END:variables
}
